package data;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;

public class Route {
    private Integer id; //Поле не может быть null, Значение поля должно быть больше 0, Значение этого поля должно быть уникальным, Значение этого поля должно генерироваться автоматически
    private String name; //Поле не может быть null, Строка не может быть пустой
    private Coordinates coordinates; //Поле не может быть null
    private java.time.LocalDate creationDate; //Поле не может быть null, Значение этого поля должно генерироваться автоматически
    private Location from; //Поле может быть null
    private Location to; //Поле не может быть null
    private double distance; //Значение поля должно быть больше 1

    /**
     * Base class that is stored in database
     * @param id id of the route, autogenerated when created
     * @param coordinates coordinates of the route, nonnull parameter
     * @param creationDate date when the route was created, autogenerated when created
     * @param distance distance of the route
     * @param to location "to" of the route, cannot be null
     * @param from location "from" of the route, can be null
     * @param name name of the route, nonnull parameter
     */
    @JsonCreator
    public Route(
            @JsonProperty("id") Integer id,
            @JsonProperty("coordinates") Coordinates coordinates,
            @JsonProperty("creationDate") LocalDate creationDate,
            @JsonProperty("distance") double distance,
            @JsonProperty("to") Location to,
            @JsonProperty("from") Location from,
            @JsonProperty("name") String name) {
        this.id = id;
        this.coordinates = coordinates;
        this.creationDate = creationDate;
        this.distance = distance;
        this.to = to;
        this.from = from;
        this.name = name;
    }
    public String getName() {
        return name;
    }
    public Integer getId() {
        return id;
    }
    public double getDistance() {
        return distance;
    }
    public Location getFrom() {
        return from;
    }
    public Coordinates getCoordinates() {
        return coordinates;
    }
    public LocalDate getCreationDate() {
        return creationDate;
    }
    public Location getTo() {
        return to;
    }

    /**
     * overridden method to use in need of printing the route
     * @return printable string representation of the route
     */
    @Override
    public String toString() {
        return "id: \t\t\t\t" + id + "\n" +
                "name:\t\t\t\t" + name + "\n" +
                "coordinates:\n" + coordinates.toString() + "\n" +
                "creation date:\t\t" + creationDate.toString() + "\n" +
                "from:\t\t\t\t" + ((from != null) ? ("\n" + from.toString()) : "null") + "\n" +
                "to:\n" + to.toString() + "\n" +
                "distance:\t\t\t" + distance + "\n";
    }
}
